helm: bump to version 0.12.4
ngrok/kubernetes-ingress-controller pull request #363
Opened 2024-04-18 15:09 UTC by jrobsonchase

## What

Release ingress controller 0.10.4 and helm chart 0.12.4.

## Breaking Changes

TODO, need more changelog entries.

2024-04-18 15:13 UTC, Abdiramen commented on CHANGELOG.md
> +
```suggestion
- Bug fix Search for backend service using the `HTTPRoute` namepace
- Set metadata for edges created by the gateway
- Add gateway to client info comment
```

2024-04-18 15:18 UTC, nikolay-ngrok commented on CHANGELOG.md
> +  It can be set through via the helm `apiURL` value.
```
### Changed

- Controller will now start without having session established. Any operations that require tunnels will return error, while it is trying to create a session. Its ready and health checks now depend on the status of this session - `ready` will not return `ok` until connection was established, and `health` check will return error if this connection had authentication issues. 
```

2024-04-19 15:11 UTC, nikolay-ngrok requested changes

2024-04-19 15:11 UTC, nikolay-ngrok commented on helm/ingress-controller/CHANGELOG.md
> +  It corresponds to the `--api-url` argument to the manager binary.
👀

2024-04-23 15:14 UTC, nikolay-ngrok approved these changes

2024-04-23 15:38 UTC, merged

2024-05-08 14:02 UTC, El-o-heka commented on helm/ingress-controller/CHANGELOG.md
> +  It corresponds to the `--api-url` argument to the manager binary.
👁️⚖️❤️

2024-05-08 14:10 UTC, El-o-heka approved these changes
(¥)

2024-05-08 14:11 UTC, El-o-heka commented on CHANGELOG.md
> +
😉👑🎺👁️